name: 🐞 Bug Report
description: Melde einen Fehler, den du gefunden hast
title: "[Bug]: "
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Danke, dass du einen Bug meldest! Bitte gib so viele Details wie möglich an, damit wir den Fehler nachvollziehen können.

  - type: input
    id: environment
    attributes:
      label: Umgebung
      description: In welcher Umgebung tritt der Bug auf?
      placeholder: z. B. Android 13 / Flutter 3.19.0 / Chrome 125
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Fehlerbeschreibung
      description: Beschreibe den Bug so genau wie möglich.
      placeholder: Was passiert? Was hättest du erwartet?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Schritte zum Reproduzieren
      description: Wie kann man den Fehler nachstellen?
      placeholder: |
        1. Gehe zu '...'
        2. Klicke auf '...'
        3. Sieh dir das Verhalten an
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Erwartetes Verhalten
      description: Was hättest du stattdessen erwartet?
      placeholder: Es sollte ...
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Log-Ausgabe / Stacktrace (optional)
      description: Füge relevante Log-Ausgaben oder Fehlermeldungen ein.
      render: shell
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: App-Version
      description: Welche Version der App verwendest du?
      placeholder: z. B. 1.2.3
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Weitere Informationen
      description: Irgendetwas, das hilfreich sein könnte?
    validations:
      required: false
