blank_issues_enabled: false
contact_links:
  - name: 💬 Community Support
    url: https://github.com/Yellotools-GmbH/-MediaMeter_Pro/discussions
    about: Für allgemeine Fragen oder Hilfe nutze bitte die Discussions.
